// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vegefood.Models;

#nullable disable

namespace Vegefood.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20230226091904_AddCartAndOrder")]
    partial class AddCartAndOrder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Vegefood.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Vegefood.Models.CartItems", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Vegefood.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Vegefood.Models.OrderItems", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Vegefood.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until.",
                            Image = "images/product-1.png",
                            IsFeatured = true,
                            Name = "Bell Pepper",
                            Price = 12m,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 2,
                            Description = "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until.",
                            Image = "images/product-2.jpg",
                            IsFeatured = true,
                            Name = "Strawberry",
                            Price = 9m,
                            Quantity = 15
                        },
                        new
                        {
                            ID = 3,
                            Description = "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until.",
                            Image = "images/product-3.jpg",
                            IsFeatured = false,
                            Name = "Green Beans",
                            Price = 7m,
                            Quantity = 200
                        },
                        new
                        {
                            ID = 4,
                            Description = "A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until.",
                            Image = "images/product-4.jpg",
                            IsFeatured = true,
                            Name = "Purple Cabbage",
                            Price = 10m,
                            Quantity = 30
                        },
                        new
                        {
                            ID = 5,
                            Description = "The big red tomato is one of the nutritions that you must have.",
                            Image = "images/product-5.jpg",
                            IsFeatured = false,
                            Name = "Tomato",
                            Price = 18m,
                            Quantity = 10
                        },
                        new
                        {
                            ID = 6,
                            Description = "This spiky and layered looking vegetable is defenitely a good choice.",
                            Image = "images/product-6.jpg",
                            IsFeatured = false,
                            Name = "Broccoli",
                            Price = 17m,
                            Quantity = 150
                        },
                        new
                        {
                            ID = 7,
                            Description = "A orange veggie is one of the best things to have in your warm soup.",
                            Image = "images/product-7.jpg",
                            IsFeatured = false,
                            Name = "Carrots",
                            Price = 24m,
                            Quantity = 20
                        },
                        new
                        {
                            ID = 8,
                            Description = "Drink more juice to have a healthier body and digestion.",
                            Image = "images/product-8.jpg",
                            IsFeatured = false,
                            Name = "Fruit Juice",
                            Price = 29m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 9,
                            Description = "Onion, something that your curry soup cannot live without.",
                            Image = "images/product-9.jpg",
                            IsFeatured = false,
                            Name = "Onion",
                            Price = 26m,
                            Quantity = 30
                        },
                        new
                        {
                            ID = 10,
                            Description = "An apple a day keeps the doctor away.",
                            Image = "images/product-10.jpg",
                            IsFeatured = false,
                            Name = "Apple",
                            Price = 22m,
                            Quantity = 300
                        },
                        new
                        {
                            ID = 11,
                            Description = "Keep accompany of your casual garlic bread breakfast!",
                            Image = "images/product-11.jpg",
                            IsFeatured = false,
                            Name = "Garlic",
                            Price = 22m,
                            Quantity = 70
                        },
                        new
                        {
                            ID = 12,
                            Description = "Something dangerous for your mouth, but still you want to bite into it.",
                            Image = "images/product-12.jpg",
                            IsFeatured = false,
                            Name = "Chili",
                            Price = 22m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("Vegefood.Models.CartItems", b =>
                {
                    b.HasOne("Vegefood.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vegefood.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Vegefood.Models.OrderItems", b =>
                {
                    b.HasOne("Vegefood.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vegefood.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
